name: rick_and_morty_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_svg: ^2.2.3
  go_router: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/arrowLeft.svg
    - assets/icons/characters.svg
    - assets/icons/close.svg
    - assets/icons/disableSort.svg
    - assets/icons/episodes.svg
    - assets/icons/eye.svg
    - assets/icons/filter.svg
    - assets/icons/grid.svg
    - assets/icons/line.svg
    - assets/icons/list.svg
    - assets/icons/locations.svg
    - assets/icons/password.svg
    - assets/icons/person.svg
    - assets/icons/search.svg
    - assets/icons/settings.svg
    - assets/icons/sortByAscending.svg
    - assets/icons/sortByDescending.svg
    - assets/images/characterNotFound.png
    - assets/images/filterNotFound.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
